"""Public API for the policy-driven AJL digital compiler."""

from .compiler import (
    LEVEL_4_STATUS,
    AJLCompiler,
    HadamardTestCompilation,
    register_signature,
)
from .evaluation import (
    DEFAULT_SHOTS,
    AJLJonesEvaluator,
    EvaluationCircuitLevel,
    EvaluationMethod,
    HadamardComponentEstimate,
    JonesEvaluation,
    PathAmplitudeEstimate,
    evaluate_jones,
)
from .lowering import assert_level_2_contract, assert_level_3_contract
from .model import (
    TOL,
    AJLPathModel,
    BraidGenerator,
    BraidWord,
    HadamardPart,
    clean_complex,
    coerce_braid_word,
)
from .policies import (
    CleanAncillaMCX,
    CompilerConfig,
    GrayCodeMCR,
    HeightSynthesisPolicy,
    Level3Policy,
    MCPhaseDecomposer,
    MCRDecomposer,
    MCXDecomposer,
    MultiplexedHeightSynthesis,
    NoAncillaMCX,
    RecursiveMCPhase,
    SwitchCaseHeightSynthesis,
)
from .primitives import (
    QuantumAdder,
    append_controlled_rotation,
    append_fixed_height_braid,
    append_hadamard_readout,
    append_phase_on_all_ones,
    append_phase_on_one,
    append_rank_one_braid_phase,
    append_standard_toffoli,
    append_uniformly_controlled_rotation,
    append_uniformly_controlled_ry,
    controlled_varphi_gate,
    gray_code_rotation_angles,
    prepare_basis_path,
)
from .reference import DenseAJLReference
from .reporting import (
    circuit_gate_count_depth,
    compilation_summary,
    level_1_varphi_names,
    level_2_gate_family_counts,
    level_3_gate_family_counts,
    print_compilation_summary,
)

__all__ = [
    "AJLCompiler",
    "AJLJonesEvaluator",
    "AJLPathModel",
    "BraidGenerator",
    "BraidWord",
    "CleanAncillaMCX",
    "CompilerConfig",
    "DenseAJLReference",
    "EvaluationCircuitLevel",
    "EvaluationMethod",
    "GrayCodeMCR",
    "HadamardComponentEstimate",
    "HadamardPart",
    "HadamardTestCompilation",
    "HeightSynthesisPolicy",
    "LEVEL_4_STATUS",
    "Level3Policy",
    "JonesEvaluation",
    "MCPhaseDecomposer",
    "MCRDecomposer",
    "MCXDecomposer",
    "MultiplexedHeightSynthesis",
    "NoAncillaMCX",
    "QuantumAdder",
    "PathAmplitudeEstimate",
    "RecursiveMCPhase",
    "SwitchCaseHeightSynthesis",
    "TOL",
    "DEFAULT_SHOTS",
    "append_controlled_rotation",
    "append_fixed_height_braid",
    "append_hadamard_readout",
    "append_phase_on_all_ones",
    "append_phase_on_one",
    "append_rank_one_braid_phase",
    "append_standard_toffoli",
    "append_uniformly_controlled_rotation",
    "append_uniformly_controlled_ry",
    "assert_level_2_contract",
    "assert_level_3_contract",
    "circuit_gate_count_depth",
    "clean_complex",
    "coerce_braid_word",
    "compilation_summary",
    "controlled_varphi_gate",
    "evaluate_jones",
    "gray_code_rotation_angles",
    "level_1_varphi_names",
    "level_2_gate_family_counts",
    "level_3_gate_family_counts",
    "prepare_basis_path",
    "print_compilation_summary",
    "register_signature",
]
